name: Build Image

on:
  push:
    branches:
      - corde

jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: karitham
          password: ${{ secrets.GR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/karitham/waifubot:corde
          cache-from: type=registry,ref=karitham/waifuBot:corde
          cache-to: type=inline
